export const FETCH_SINGLEPOST_REQUEST = 'FETCH_SINGLEPOST_REQUEST'
export const FETCH_SINGLEPOST_SUCCESS = 'FETCH_SINGLEPOST_SUCCESS'
export const FETCH_SINGLEPOST_FAILURE = 'FETCH_SINGLEPOST_FAILURE'
export const POSTID = 'POSTID'